#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDC_BACK                                1099
#define IDC_Y                                   1101
#define IDC_N                                   1102
#define IDC_SLIDER1                             1211
#define IDC_SLIDER2                             1212
#define IDC_SLIDER3                             1213
#define IDC_SLIDER4                             1214
#define IDC_SMIN1                               1221
#define IDC_SMIN2                               1222
#define IDC_SMIN3                               1223
#define IDC_SMIN4                               1224
#define IDC_SMAX1                               1231
#define IDC_SMAX2                               1232
#define IDC_SMAX3                               1233
#define IDC_SMAX4                               1234
#define IDC_EDIT1                               1241
#define IDC_EDIT2                               1242
#define IDC_EDIT3                               1243
#define IDC_EDIT4                               1244
#define IDC_WHO                                 1301
#define IDC_EDITNAME                            1302
#define IDC_RADIOLOCAL                          1311
#define IDC_RADIOAUTO                           1312
#define IDC_RADIOREMOTE                         1313
#define IDC_IPADDRESS1                          1321
#define IDM_NEW                                 6000
#define IDM_OPEN                                6001
#define IDM_REOPEN                              6002
#define IDM_REVERT                              6003
#define IDM_SAVE                                6004
#define IDM_SAVE_AS                             6005
#define IDM_CLOSE                               6006
#define IDM_PRINT                               6007
#define IDM_EXIT                                6008
#define IDM_PLAY_PLAY                           6100
#define IDM_TAKE_BACK                           6101
#define IDM_HINT                                6102
#define IDM_PAUSE                               6103
#define IDM_PASS                                6104
#define IDM_RESIGN                              6105
#define IDM_RESTART                             6106
#define IDM_UNDO                                6107
#define IDM_REDO                                6108
#define IDM_AUTOPAUSE                           6109
#define IDM_SMALL_TILES                         6200
#define IDM_MEDIUM_TILES                        6201
#define IDM_LARGE_TILES                         6202
#define IDM_RECENTER                            6203
#define IDM_ATTRIBUTES                          6204
#define IDM_SHOW_CLOCKS                         6205
#define IDM_SHOW_GRID                           6206
#define IDM_SHOW_HINTS                          6207
#define IDM_SHOW_SCORES                         6208
#define IDM_SHOW_TILES                          6209
#define IDM_ANIMATION                           6210
#define IDM_AUTOCENTER                          6211
#define IDM_RULES                               6900
#define IDM_WARRANTY                            6901
#define IDM_ABOUT                               6902
