#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDC_EDIT1                               1001
#define IDC_EDIT2                               1002
#define IDC_EDIT3                               1003
#define IDC_EDIT4                               1004
#define IDC_SLIDER1                             1011
#define IDC_SLIDER2                             1012
#define IDC_SLIDER3                             1013
#define IDC_SLIDER4                             1014
#define IDC_SMIN1                               1021
#define IDC_SMIN2                               1022
#define IDC_SMIN3                               1023
#define IDC_SMIN4                               1024
#define IDC_SMAX1                               1031
#define IDC_SMAX2                               1032
#define IDC_SMAX3                               1033
#define IDC_SMAX4                               1034
#define IDC_Y                                   1101
#define IDC_N                                   1102
#define IDM_NEW                                 6000
#define IDM_OPEN                                6001
#define IDM_REOPEN                              6002
#define IDM_REVERT                              6003
#define IDM_SAVE                                6004
#define IDM_SAVE_AS                             6005
#define IDM_CLOSE                               6006
#define IDM_PRINT                               6007
#define IDM_EXIT                                6008
#define IDM_PLAY_PLAY                           6100
#define IDM_TAKE_BACK                           6101
#define IDM_HINT                                6102
#define IDM_PAUSE                               6103
#define IDM_PASS                                6104
#define IDM_RESIGN                              6105
#define IDM_RESTART                             6106
#define IDM_UNDO                                6107
#define IDM_REDO                                6108
#define IDM_AUTOPAUSE                           6109
#define IDM_SMALL_TILES                         6200
#define IDM_MEDIUM_TILES                        6201
#define IDM_LARGE_TILES                         6202
#define IDM_RECENTER                            6203
#define IDM_ATTRIBUTES                          6204
#define IDM_SHOW_CLOCKS                         6205
#define IDM_SHOW_GRID                           6206
#define IDM_SHOW_HINTS                          6207
#define IDM_SHOW_SCORES                         6208
#define IDM_SHOW_TILES                          6209
#define IDM_ANIMATION                           6210
#define IDM_AUTOCENTER                          6211
#define IDM_RULES                               6900
#define IDM_WARRANTY                            6901
#define IDM_ABOUT                               6902
