#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDC_BACK                                1099
#define IDC_Y                                   1101
#define IDC_N                                   1102
#define IDC_RADIODEBUG                          1201
#define IDC_RADIOFRIENDLY                       1202
#define IDC_RADIOPRACTICE                       1203
#define IDC_RADIOCHALLENGE                      1204
#define IDC_SLIDERMINUTES                       1205
#define IDC_EDITMINUTES                         1206
#define IDC_CHECKBOX_RANDOMIZE                  1207
#define IDC_EDIT_SEED                           1208
#define IDC_ENDLESS                             1301
#define IDC_RECT                                1302
#define IDC_TORUS                               1303
#define IDC_VSTRIP                              1304
#define IDC_HSTRIP                              1305
#define IDC_VCYLINDER                           1306
#define IDC_HCYLINDER                           1307
#define IDC_TRIANGLE                            1311
#define IDC_4WAY                                1312
#define IDC_HEX                                 1313
#define IDC_8WAY                                1314
#define IDC_GRIDIMAGE                           1319
#define IDC_EDITHEIGHT                          1321
#define IDC_EDITWIDTH                           1322
#define IDC_CELLCNT                             1328
#define IDC_RECALC                              1329
#define IDC_COMBINATIONS                        1401
#define IDC_CLONES                              1402
#define IDC_TOTAL_TILES                         1403
#define IDC_SLIDER1                             1411
#define IDC_SLIDER2                             1412
#define IDC_SLIDER3                             1413
#define IDC_SLIDER4                             1414
#define IDC_SLIDER5                             1415
#define IDC_SMIN1                               1421
#define IDC_SMIN2                               1422
#define IDC_SMIN3                               1423
#define IDC_SMIN4                               1424
#define IDC_SMIN5                               1425
#define IDC_SMAX1                               1431
#define IDC_SMAX2                               1432
#define IDC_SMAX3                               1433
#define IDC_SMAX4                               1434
#define IDC_SMAX5                               1435
#define IDC_EDIT1                               1441
#define IDC_EDIT2                               1442
#define IDC_EDIT3                               1443
#define IDC_EDIT4                               1444
#define IDC_EDIT5                               1445
#define IDC_WHO                                 1501
#define IDC_EDITNAME                            1502
#define IDC_RADIOLOCAL                          1511
#define IDC_RADIOAUTO                           1512
#define IDC_RADIOREMOTE                         1513
#define IDC_IPADDRESS1                          1521
#define IDC_RADIO_NONE                          1601
#define IDC_RADIO_EMPTY                         1602
#define IDC_RADIO_CONNECTED                     1603
#define IDC_RADIO_USABLE_ANY                    1604
#define IDC_RADIO_USABLE_SELECTED               1605
#define IDC_LIST1                               1701
#define IDC_LIST2                               1702
#define IDC_LIST3                               1703
#define IDC_LIST4                               1704
#define IDC_LIST5                               1705
#define IDM_UP                                  5000
#define IDM_DOWN                                5001
#define IDM_LEFT                                5002
#define IDM_RIGHT                               5003
#define IDM_NEW                                 6000
#define IDM_OPEN                                6001
#define IDM_REOPEN                              6002
#define IDM_REVERT                              6003
#define IDM_SAVE                                6004
#define IDM_SAVE_AS                             6005
#define IDM_CLOSE                               6006
#define IDM_PRINT                               6007
#define IDM_EXIT                                6008
#define IDM_PLAY_PLAY                           6100
#define IDM_TAKE_BACK                           6101
#define IDM_SUGGEST                             6102
#define IDM_PAUSE                               6103
#define IDM_SWAP_ALL                            6104
#define IDM_PASS                                6105
#define IDM_RESIGN                              6106
#define IDM_RESTART                             6107
#define IDM_UNDO                                6108
#define IDM_REDO                                6109
#define IDM_AUTOPAUSE                           6110
#define IDM_RECENTER                            6202
#define IDM_ATTRIBUTES                          6203
#define IDM_HINTS                               6204
#define IDM_SHOW_CLOCKS                         6205
#define IDM_SHOW_GRID                           6206
#define IDM_SHOW_SCORES                         6207
#define IDM_PEEK                                6208
#define IDM_ANIMATION                           6209
#define IDM_BS_ZOOM_OUT                         6220
#define IDM_BS1                                 6221
#define IDM_BS2                                 6222
#define IDM_BS3                                 6223
#define IDM_BS4                                 6224
#define IDM_BS5                                 6225
#define IDM_BS6                                 6226
#define IDM_BS7                                 6227
#define IDM_BS_ZOOM_IN                          6228
#define IDM_TS1                                 6231
#define IDM_TS2                                 6232
#define IDM_TS3                                 6233
#define IDM_TS4                                 6234
#define IDM_TS5                                 6235
#define IDM_TS6                                 6236
#define IDM_TS7                                 6237
#define IDM_CANCEL                              6301
#define IDM_RULES                               6900
#define IDM_WARRANTY                            6901
#define IDM_ABOUT                               6902
